"""This module handles cryptographically signing requests sent to the site.

This code was largely generated by Claude based off the dailyprog.club app code.
`sign_submission()` is the primary entry point.
"""

import base64
import datetime
import hashlib
import json
import os
import pathlib
import secrets
from typing import TypedDict

from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization

SIGNING_DOMAIN = "dailyprog-solve-v1"
PRACTICE_SIGNING_DOMAIN = "dailyprog-practice-v1"

class SignedSubmission(TypedDict):
    publicKey: str
    signature: str
    nonce: str
    timestamp: str

def to_base64url(data: bytes) -> str:
    """Encode bytes to unpadded base64url string matching TypeScript toBase64Url."""
    return base64.urlsafe_b64encode(data).decode("utf-8").rstrip("=")

def encode_public_key(alg: str, raw_bytes: bytes) -> str:
    return f"{alg}:{to_base64url(raw_bytes)}"

def hash_solution(code: str) -> str:
    """SHA-256 (hex) of the submitted source string."""
    return hashlib.sha256(code.encode("utf-8")).hexdigest()

def build_signing_message(puzzle_id: str, solution_hash: str, nonce: str, timestamp: str) -> bytes:
    """Domain-tagged fixed-order newline-joined byte message for verified solves."""
    fields = [SIGNING_DOMAIN, puzzle_id, solution_hash, nonce, timestamp]
    return "\n".join(fields).encode("utf-8")

def load_private_key() -> ed25519.Ed25519PrivateKey:
    raw_b64 = json.loads((pathlib.Path(os.environ["XDG_DATA_HOME"]) /  "dailyprog.club/keys.json").read_text())["rawPrivateKey"]
    padding = "=" * (-len(raw_b64) % 4)
    private_key_bytes = base64.urlsafe_b64decode(raw_b64 + padding)
    return ed25519.Ed25519PrivateKey.from_private_bytes(private_key_bytes)

def sign_submission(
    puzzle_id: str,
    code: str,
    nonce: str | None = None,
    timestamp: str | None = None,
) -> SignedSubmission:
    """
    Package and sign a solution submission matching @dailyprog/app identity-protocol.ts
    """
    private_key = load_private_key()
    if nonce is None:
        nonce = secrets.token_hex(16)
    if timestamp is None:
        timestamp = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0, tzinfo=None).isoformat() + ".00Z"

    solution_hash = hash_solution(code)
    message_bytes = build_signing_message(puzzle_id, solution_hash, nonce, timestamp)
    
    # Sign message
    signature_bytes = private_key.sign(message_bytes)
    
    # Export public key
    public_key = private_key.public_key()
    raw_public_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw
    )

    return {
        "publicKey": encode_public_key("ed25519", raw_public_bytes),
        "signature": to_base64url(signature_bytes),
        "nonce": nonce,
        "timestamp": timestamp,
    }
